    - name: Create systemd service for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Monitoring
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_group }}
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus \
            --web.console.templates=/usr/local/bin/consoles \
            --web.console.libraries=/usr/local/bin/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Cleanup temporary Prometheus files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ prometheus_tarball }}"
        - "{{ prometheus_extract_dir }}"

                                              